GET localhost:9000/api/my-page/tour
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0bGZlbTMzMTVAbmF2ZXIuY29tIiwiZXhwIjoyNTg2MzkyNzk0LCJpc3MiOiJmaW5kbXlndWlkZS5jb20ifQ.Q-5RYWDpiDImCvKtJ7etS6zzxCGArs9Smn3XtXMjtIo