GET localhost:9000/api/my-page/tour
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ4b2RuanM4Mjg3QG5hdmVyLmNvbSIsImV4cCI6MjU4NjA1NTA0OCwiaXNzIjoiZmluZG15Z3VpZGUuY29tIn0.UA0LgpjvR0IMOxACvlNBqqCkCHqU1qMhlY15Xsgj93E