POST http://localhost:9000/api/guide-like/101
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0bGZlbTMzMTVAbmF2ZXIuY29tIiwiZXhwIjoyNTg2MzA0MjgxLCJpc3MiOiJmaW5kbXlndWlkZS5jb20ifQ.58vptYy0T4EnY8l9BK-5q22eLqHvg1x9I6L6Pfm-HxY

###
GET http://localhost:9000/api/guide-like/guide-list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0bGZlbTMzMTVAbmF2ZXIuY29tIiwiZXhwIjoyNTg2MzA0MjgxLCJpc3MiOiJmaW5kbXlndWlkZS5jb20ifQ.58vptYy0T4EnY8l9BK-5q22eLqHvg1x9I6L6Pfm-HxY

###
GET http://localhost:9000/api/find-my-guide/guide/reviews/2
Content-Type: application/json