POST http://localhost:9000/api/tourProduct/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0bGZlbTMzMTVAbmF2ZXIuY29tIiwiZXhwIjoyNTg2MzkyNzk0LCJpc3MiOiJmaW5kbXlndWlkZS5jb20ifQ.Q-5RYWDpiDImCvKtJ7etS6zzxCGArs9Smn3XtXMjtIo

{

  "title": "잠이 깔끼",
  "content": "잠이 깔끼하게 오는 투어",
  "price": 200000,
  "languages" : ["영어","포르투갈어"],
  "howManyDay": ["2","3"],
  "location": [
    {
      "date": "1",
      "title": "우리집",
      "coordinates": [12.2131, 14.3213]
    },
    {
      "date": "2",
      "title": "우리집2",
      "coordinates": [12.5, 12.123]
    }
  ],
  "themeIds": [1],
  "availableDates": ["2032-12-01","2032-12-02","2023-12-03"]
}


###
//관광상품 예약
POST http://localhost:9000/api/tourProduct/reserve-tour/197
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ4b2RuanM4Mjg3QG5hdmVyLmNvbSIsImV4cCI6MjU4NjQ2NzI1NCwiaXNzIjoiZmluZG15Z3VpZGUuY29tIn0.F01JoAQIuL8MdwmcGwVzTAtIiL5mB5KIBcvC0kze5tc
Content-Type: application/json

{
  "email": "xodnjs8287@naver.com",
  "startDate": "2022-12-01",
  "endDate": "2022-12-03"
}

###
//관광상품 예약
POST http://localhost:9000/api/tourProduct/reserve-tour/by-guide/673
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0bGZlbTMzMTVAbmF2ZXIuY29tIiwiZXhwIjoyNTg2MzIzNzkzLCJpc3MiOiJmaW5kbXlndWlkZS5jb20ifQ.ctF2CnS1mNnlURJuOl2ss494D7PmOOxZWDraS98wwGQ
Content-Type: application/json

###
//예약된 투어 삭제
POST http://localhost:9000/api/tourProduct/delete-reserved-tour/57
Content-Type: application/json
Authorization:

###
// 테마 등록
POST http://localhost:9000/api/postTheme
Content-Type: application/json

{
  "themeTitle": "기타"
}

###




