POST http://localhost:9000/api/tourProduct/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ4b2RuanM4Mjg3QG5hdmVyLmNvbSIsImV4cCI6MjU4NjE5MTY2MywiaXNzIjoiZmluZG15Z3VpZGUuY29tIn0._iowROEfXjPJOp32toobX7ZLuNMrHLuuig0Xd2-da44

{

  "title": "Tour images test",
  "content": "Tour Description test images",
  "price": 200000,
  "languages" : ["KOREAN"],
  "howManyDay": ["2","3"],
  "location": [
    {
      "title": "해운대 암소갈비",
      "coordinates": [12.2131, 14.3213]
    },
    {
      "title": "맛있는 음식점2",
      "coordinates": [12.5, 12.123]
    }
  ],
  "themeIds": [1],
  "availableDates": ["2023-12-01","2023-12-02","2023-12-03"],
  "images": ["image1","image2"]

}


###
//관광상품 예약
POST http://localhost:9000/api/tourProduct/reserve-tour/184
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0bGZlbTMzMTVAbmF2ZXIuY29tIiwiZXhwIjoyNTg2MTkxMzU3LCJpc3MiOiJmaW5kbXlndWlkZS5jb20ifQ.FInIxLo5yc37cXbKQuRWkLkXOrKC54-_3OanrFbJQrc
Content-Type: application/json

{
  "email": "tlfem3315@naver.com",
  "startDate": "2023-12-01",
  "endDate": "2023-12-03"
}


###

// 테마 등록
POST http://localhost:9000/api/postTheme
Content-Type: application/json

{
  "themeTitle": "애견동반"
}

###




