POST http://localhost:9000/api/tourProduct/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ4b2RuanMxODM3QGdtYWlsLmNvbSIsImV4cCI6MjU4NDA3MjQ2MywiaXNzIjoiZmluZG15Z3VpZGUuY29tIn0.1z1SH_qNhnY4qbX_azxDOQh9zz4TjOPTTLHCSV_2Um4

{

  "title": "Tour Title",
  "content": "Tour Description",
  "price": 120000,
  "languages" : ["JAPANESE"],
  "howManyDay": ["1","2"],
  "location": [
    {
      "title": "해운대 암소갈비",
      "coordinates": [12.2131, 14.3213]
    },
    {
      "title": "맛있는 음식점2",
      "coordinates": [12.5, 12.123]
    }
  ],
  "themeIds": [1],
  "availableDates": ["2022-08-01","2022-07-01","2022-07-02"]

}


###
//관광상품 예약
POST http://localhost:9000/api/tourProduct/reserve-tour/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ4b2RuanMxODM3QGdtYWlsLmNvbSIsImV4cCI6MjU4NTk1NzgyOSwiaXNzIjoiZmluZG15Z3VpZGUuY29tIn0.ivIHXcw5dqTFGYfw2DJz40H39lWLhopvKLizTcqyjxM

Content-Type: application/json

{
  "email": "xodnjs1837@naver.com",
  "startDate": "2022-08-01",
  "endDate": "2022-08-01"
}


###


// 테마 등록
POST http://localhost:9000/api/postTheme
Content-Type: application/json

{
  "themeTitle": "애견동반"
}

###




