###
//전체 상품 목록 조회
GET https://find-my-guide.site/api/tourProducts
Content-Type: application/json

###
//하나의 상품 조회
GET http://localhost:9000/api/tourProduct/2
Content-Type: application/json

###
//좋아요순 조회
GET http://localhost:9000/tourProducts/likes
Content-Type: application/json

###
//장소로 조회
GET http://localhost:9000/api/tourProducts/search?title=해운대 암소갈비
Content-Type: application/json

###
//top10 관광상품 조회
GET http://localhost:9000/api/tourProduct/top-10
Content-Type: application/json

###
//테마별 조회
GET http://find-my-guide.site/api/tourProducts/search-theme?title=애견동반
Content-Type: application/json

###
//완료된 상품 조회
GET http://localhost:9000/api/my-page/reservation/completed-tours
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ4b2RuanM4Mjg3QG5hdmVyLmNvbSIsImV4cCI6MjU4NjE0Mzk2OSwiaXNzIjoiZmluZG15Z3VpZGUuY29tIn0.bUOHDMYwX32NGJ4IWquW3E64yX1vcuDEo2FiboZ53gM
###
//
GET http://localhost:9000/api/my-page/reservation/upcoming-tours
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ4b2RuanM4Mjg3QG5hdmVyLmNvbSIsImV4cCI6MjU4NjE0NjE5NywiaXNzIjoiZmluZG15Z3VpZGUuY29tIn0.k95kaEpvsEMQy78htT61me6cWXNal9sgIT5FYrza1pY


###
GET localhost:9000/api/tourProduct/top-10
Content-Type: application/json