POST localhost:9000/api/want-tourProduct/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0bGZlbTMzMTVAbmF2ZXIuY29tIiwiZXhwIjoyNTg2MzA0NzEyLCJpc3MiOiJmaW5kbXlndWlkZS5jb20ifQ.GBUme6o8EquojLp17O3tg4TPlDDGfbmyy6xshRHZiXs

{
  "title" : "원하는투어2323",
  "content": "원하는투어1111",
  "price" : 100000112,
  "vehicle": "대중교통",
  "totalPeople": 2,
  "location": [
    {
      "title": "해운대 암소갈비"
    },
    {
      "title": "맛있는 음식점2"
    }
  ],
  "themeIds": [1,2],
  "wantDates" : ["2027-08-01", "2027-08-02", "2027-08-03"]
}


###

POST localhost:9000/api/want-tourProduct/update/673
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0bGZlbTMzMTVAbmF2ZXIuY29tIiwiZXhwIjoyNTg2NDU0OTgzLCJpc3MiOiJmaW5kbXlndWlkZS5jb20ifQ.hCueEsoWgCPswS9KCio4NLzJbzrjF9MSixkUXkCFxxg
Content-Type: application/json

{
  "price": 500
}
###
GET localhost:8080/wantTourProduct/20
Content-Type: application/json

###
DELETE localhost:9000/api/want-tourProduct/delete/595
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0bGZlbTMzMTVAbmF2ZXIuY29tIiwiZXhwIjoyNTg2Mzk5NTA5LCJpc3MiOiJmaW5kbXlndWlkZS5jb20ifQ.aLpzIQ-3E5JvXYf1G6AcwXe_ndHqVW9PosQKYsfNz_o

###
