POST localhost:9000/api/want-tourProduct/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0bGZlbTMzMTVAZ21haWwuY29tIiwiZXhwIjoyNTg2NjY3ODQxLCJpc3MiOiJmaW5kbXlndWlkZS5jb20ifQ.7pB9CgxRv-jP9RaI_Qws-oNQQSEuqP9mXOa6XR_TfSA

{
  "title" : "바뀐다고?",
  "content": "안돼!~",
  "price" : 1000,
  "vehicle": "대중교통",
  "totalPeople": 2,
  "location": [
    {
      "title": "광안리 암소갈비"
    },
    {
      "title": "맛있는 음식점2"
    }
  ],
  "themeIds": [1,2],
  "wantDates" : ["2027-08-01", "2027-08-02", "2027-08-03"]
}


###

POST localhost:9000/api/want-tourProduct/update/840
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0bGZlbTMzMTVAZ21haWwuY29tIiwiZXhwIjoyNTg2NjY3ODQxLCJpc3MiOiJmaW5kbXlndWlkZS5jb20ifQ.7pB9CgxRv-jP9RaI_Qws-oNQQSEuqP9mXOa6XR_TfSA
Content-Type: application/json

{
  "vehicle": "자전거",
  "content": "바뀌었네!!",
  "price": 2450
}
###
GET localhost:8080/wantTourProduct/20
Content-Type: application/json

###
DELETE localhost:9000/api/want-tourProduct/delete/595
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0bGZlbTMzMTVAbmF2ZXIuY29tIiwiZXhwIjoyNTg2Mzk5NTA5LCJpc3MiOiJmaW5kbXlndWlkZS5jb20ifQ.aLpzIQ-3E5JvXYf1G6AcwXe_ndHqVW9PosQKYsfNz_o

###
