POST localhost:9000/api/tour-product-review/register/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ4b2RuanMxODM3QGdtYWlsLmNvbSIsImV4cCI6MjU4NDA3MjQ2MywiaXNzIjoiZmluZG15Z3VpZGUuY29tIn0.1z1SH_qNhnY4qbX_azxDOQh9zz4TjOPTTLHCSV_2Um4
Content-Type: application/json

{
  "content": "가나다라마바사바사  타파하 asdasdsadasdasdasdas바사바사 ",
  "rating": 3,
  "image": null
}


###
GET localhost:9000/api/tour-product-review/all
Content-Type: application/json

###
#GET find-my-guide.site/api/tour-product-review/recent-reviews/6
#Content-Type: application/json

###
GET localhost:9000/api/tour-product-review/recent-reviews
Content-Type: application/json