//회원등록
POST http://find-my-guide.site:9000/api/find-my-guide/member/initiate-sign-up
Content-Type: application/json

{
  "name" : "신대혁",
  "email" : "123qwe@naver.com",
  "password" : "qpal123!",
  "nickname" : "eqweqweqwe",
  "nationality" : "KR",
  "gender" : "FEMALE",
  "birthDate" : "19950930",
  "phoneNumber" : "010-1331-8287",
  "nationalCertificationOfGuideYn" : "Y",
  "guideProfilePicture": "",
  "guideIntroduction": "",
  "guideExperience": "",
  "languages": []
}

###

POST https://find-my-guide.site/api/find-my-guide/member/check-nickname
Content-Type: application/json

{
  "nickName": "qweqwe"
}

###

POST http://localhost:9000/api/find-my-guide/member/check-phoneNumber
Content-Type: application/json

{
  "phoneNumber": "010-4123-8287"
}

###
DELETE http://localhost:9000/api/find-my-guide/member/delete-not-certified-email?email=mko567@naver.com
Content-Type: application/json


###

POST http://localhost:9000/api/find-my-guide/member/complete-sign-up
Content-Type: application/json

{
  "email": "tlfem3315@naver.com",
  "code": "dx26D64d"
}

###

POST http://localhost:9000/api/find-my-guide/member/check-duplicate
Content-Type: application/json

{
  "email": "xodnjs8287@naver.com"
}

###

POST http://localhost:9000/api/find-my-guide/member/initiate-change-password
Content-Type: application/json

{
  "email": "tlfem3315@naver.com"
}

###
POST http://localhost:9000/api/find-my-guide/member/reset-password
Content-Type: application/json

{
  "code": "CNbzTxLi",
  "newPassword": "qpal123!"

}

###
GET http://localhost:9000/api/find-my-guide/guide/search?age=20-30
Content-Type: application/json


###
//회원 로그인
POST http://localhost:9000/api/find-my-guide/member/sign-in
Content-Type: application/json

{
  "email" : "xodnjs8287@naver.com",
  "password": "qpal123!"

}

###
POST http://localhost:9000/api/find-my-guide/member/find-email
Content-Type: application/json

{
  "name" : "장태원",
  "phoneNumber" : "010-9231-1234"

}

###

//회원조회
GET localhost:9000/api/find-my-guide/member/detail
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ4b2RuanMxODM3QGdtYWlsLmNvbSIsImV4cCI6MjU4MzY5MTA0MSwiaXNzIjoiZmluZG15Z3VpZGUuY29tIn0.BwerMGDuCKYV6SSBeVOVX5tq6GU7iHXY_2UddC1SW98
//회원수정
//비밀번호, 닉네임, 휴대폰번호, 자격증여부 필드만 변경가능
//변경할 필드만 입력하면 됨

###

//인기 가이드 조회
GET localhost:9000/api/find-my-guide/guide/popular-guide
Content-Type: application/json

###
GET localhost:9000/api/find-my-guide/guide/guides/detail/2
Content-Type: application/json

###
//전체 가이드 조회

GET localhost:9000/api/find-my-guide/member/guides
Content-Type: application/json




//회원수정
//비밀번호, 닉네임, 휴대폰번호, 자격증여부 필드만 변경가능
//변경할 필드만 입력하면 됨

###
PATCH localhost:9000/api/find-my-guide/member/update
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ4b2RuanM4Mjg3QG5hdmVyLmNvbSIsImV4cCI6MjU4NjEzMDU3OCwiaXNzIjoiZmluZG15Z3VpZGUuY29tIn0.0GBD0bFbJKubvNyg_SIIxsT_fcTRPFOy9tDhG_dYaDY
Content-Type: application/json

{
  "nickname" : "지금수정함",
  "phoneNumber" : "010-4321-1234"
}

###
//회원삭제
DELETE localhost:9000/api/find-my-guide/member/delete

###
PUT localhost:9000/api/find-my-guide/member/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ4b2RuanM4Mjg3QG5hdmVyLmNvbSIsImV4cCI6MjU4NjEzMDU3OCwiaXNzIjoiZmluZG15Z3VpZGUuY29tIn0.0GBD0bFbJKubvNyg_SIIxsT_fcTRPFOy9tDhG_dYaDY

{
  "password": "qpal123!",
  "newPassword": "qpal123!@",
  "newPasswordAgain": "qpal123!@"

}