//회원등록
POST http://localhost:9000/api/find-my-guide/member/initiate-sign-up
Content-Type: application/json

{
  "name" : "하하호",
  "email" : "xodnjs1837@gmail.com",
  "password" : "qpal123!",
  "nickname" : "qweqwe",
  "nationality" : "KR",
  "gender" : "FEMALE",
  "birthDate" : "19950930",
  "phoneNumber" : "010-4123-8287",
  "nationalCertificationOfGuideYn" : "Y"
}

###




###

POST http://localhost:9000/api/find-my-guide/member/complete-sign-up
Content-Type: application/json

{
  "email": "xodnjs8287@naver.com",
  "code": "o7xZzGgb"
}

###

POST http://localhost:9000/api/find-my-guide/member/check-duplicate
Content-Type: application/json

{
  "email": "xodnjs8287@naver.com"
}

###

POST http://localhost:9000/api/find-my-guide/member/initiate-change-password
Content-Type: application/json

{
  "email": "xodnjs8287@naver.com"
}

###
POST http://localhost:9000/api/find-my-guide/member/reset-password
Content-Type: application/json

{
  "code": "bgCr5w0g",
  "newPassword": "xodnjs783!"

}

###
GET http://localhost:9000/api/find-my-guide/guides/search?date=2022-08-01
Content-Type: application/json


###
//회원 로그인
POST http://localhost:9000/api/find-my-guide/member/sign-in
Content-Type: application/json

{
  "email" : "xodnjs1837@naver.com",
  "password": "qpal123!"

}

###
POST http://localhost:9000/api/find-my-guide/member/find-email
Content-Type: application/json

{
  "name" : "장태원",
  "phoneNumber" : "010-9231-1234"

}

###

//회원조회
GET localhost:9000/api/find-my-guide/member/detail
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ4b2RuanM4Mjg3QG5hdmVyLmNvbSIsImV4cCI6MjU4MzExODg4OSwiaXNzIjoiZmluZG15Z3VpZGUuY29tIn0.s7Sdj-qrKop5BpB7TgyKOEqI2V3-T3z6EcLPKXvu4LI
//회원수정
//비밀번호, 닉네임, 휴대폰번호, 자격증여부 필드만 변경가능
//변경할 필드만 입력하면 됨

###

//인기 가이드 조회
GET localhost:9000/api/find-my-guide/guide/popular-guide
Content-Type: application/json

###
GET localhost:9000/api/find-my-guide/guide/guides/detail/2
Content-Type: application/json

###
//전체 가이드 조회

GET localhost:9000/api/find-my-guide/member/guides
Content-Type: application/json




//회원수정
//비밀번호, 닉네임, 휴대폰번호, 자격증여부 필드만 변경가능
//변경할 필드만 입력하면 됨

###
PUT localhost:9000/api/find-my-guide/member/update
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ4b2RuanM4Mjg3QG5hdmVyLmNvbSIsImV4cCI6MjU4MzExODg4OSwiaXNzIjoiZmluZG15Z3VpZGUuY29tIn0.s7Sdj-qrKop5BpB7TgyKOEqI2V3-T3z6EcLPKXvu4LI
Content-Type: application/json

{
  "nickname" : "upgradeKKKK",
  "phoneNumber" : "010-4321-1234"
}

###
//회원삭제
DELETE localhost:9000/api/find-my-guide/member/delete