spring:
  datasource:
    url: jdbc:mysql://43.201.21.169:3306/find_my_guide
    username: root
    password: qpal12!@

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace